# frozen_string_literal: true
require 'net_cli/system_utils'

# Provides some methods to generate configuration files for netctl
class TemplateGenerator
  ##
  # This method generates a configuration for for wireless connection.
  #
  # Arguments:
  #   type: type of wireless connection it could be _:open_, _:wpa_ or _:wep_
  #
  #   interface: an interface to configure
  #
  #   essid: ESSID of wireless network
  #
  # Optional arguments:
  #   ip: ip to bind dhcp used by default
  #   hidden: by default false
  def self.wireless(type:, interface: SystemUtils::wlan_iface, key: nil,
                    priority: nil, essid:, ip: 'dhcp', hidden: false,
                    adhoc: false)
    result = <<~HEREDOC
      Description='Autogenerated configuration by net-cli'
      Interface=#{interface}
      Connection=wireless

      IP=#{ip}
      ESSID='#{essid}'
      #{'Hidden=yes' if hidden}
      #{'AdHoc=yes' if adhoc}
      #{"Priority=#{priority}" if priority}

    HEREDOC
    result += if %i(wpa wep).include? type
                <<~HEREDOC
                  Security=#{type}
                  Key=\"#{key}
                HEREDOC
              else
                "Security: none\n"
              end
    result
  end
end
